import { Inter } from "next/font/google";
import "./globals.css";

const roboto = Inter({ subsets: ["latin"], weight: ['100', '400'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
